// src/services/authService.ts
// Simulated JWT authentication service (frontend‑only). In production replace with real API calls.

import { LoginCredentials, SignUpData, User, UserRole, AuthTokenPayload, AuthState } from '../types/ecommerce';
import { observability } from './observability';

/**
 * Hard‑coded demo users. In a real app these would be validated by the backend.
 */
const demoUsers: Record<string, { password: string; role: UserRole; name: string }> = {
  'admin@vittabasics.com': {
    password: 'admin123',
    role: 'admin',
    name: 'Admin Vitta',
  },
  'cliente@vittabasics.com': {
    password: 'cliente123',
    role: 'customer',
    name: 'Cliente Vitta',
  },
};

/**
 * Encode a simple JWT‑like token (base64 header.payload.signature).
 * The payload contains the AuthTokenPayload fields. Signature is mocked.
 */
function encodeToken(payload: AuthTokenPayload): string {
  const header = btoa(JSON.stringify({ alg: 'HS256', typ: 'JWT' }));
  const body = btoa(JSON.stringify(payload));
  const signature = btoa('simulated-signature');
  return `${header}.${body}.${signature}`;
}

/**
 * Decode the payload of a token generated by `encodeToken`.
 */
function decodeToken(token: string): AuthTokenPayload | null {
  try {
    const [, body] = token.split('.');
    const json = atob(body);
    return JSON.parse(json) as AuthTokenPayload;
  } catch {
    return null;
  }
}

/**
 * Generate a fresh payload with a new expiration time.
 */
function createPayload(user: User, expiresInHours = 8): AuthTokenPayload {
  const now = Math.floor(Date.now() / 1000);
  return {
    sub: user.id,
    email: user.email,
    role: user.role,
    name: user.name,
    iat: now,
    exp: now + expiresInHours * 3600,
  };
}

/**
 * Persist token and user info in localStorage.
 */
function persistSession(user: User, token: string) {
  localStorage.setItem('auth_user', JSON.stringify(user));
  localStorage.setItem('auth_token', token);
}

/**
 * Clear persisted session.
 */
function clearSession() {
  localStorage.removeItem('auth_user');
  localStorage.removeItem('auth_token');
}

/**
 * Public API of the auth service.
 */
export const authService = {
  /**
   * Attempt to log in with email/password. Returns a Promise that resolves to
   * `{ user, token }` on success or throws an error string on failure.
   */
  async login(credentials: LoginCredentials): Promise<{ user: User; token: string }> {
    const record = demoUsers[credentials.email];
    if (!record || record.password !== credentials.password) {
      observability.captureError(new Error('Invalid credentials'));
      throw new Error('Credenciais inválidas');
    }
    const user: User = {
      id: `${record.role}-${credentials.email}`,
      name: record.name,
      email: credentials.email,
      role: record.role,
    };
    const token = encodeToken(createPayload(user));
    persistSession(user, token);
    observability.captureEvent('login_success', { email: user.email, role: user.role });
    return { user, token };
  },

  /** Register a new customer (demo only). */
  async signUp(data: SignUpData): Promise<User> {
    const user: User = {
      id: `customer-${data.email}`,
      name: data.name,
      email: data.email,
      role: 'customer',
    };
    // Store a dummy password for demo purposes.
    demoUsers[data.email] = { password: data.password, role: 'customer', name: data.name };
    const token = encodeToken(createPayload(user));
    persistSession(user, token);
    observability.captureEvent('signup_success', { email: user.email });
    return user;
  },

  /** Logout the current user. */
  logout() {
    clearSession();
    observability.captureEvent('logout');
  },

  /** Validate a stored token – checks expiration. */
  validateToken(token: string): AuthTokenPayload | null {
    const payload = decodeToken(token);
    if (!payload) return null;
    const now = Math.floor(Date.now() / 1000);
    return payload.exp > now ? payload : null;
  },

  /** Refresh an existing token (extends expiration). */
  refreshToken(token: string): string | null {
    const payload = this.validateToken(token);
    if (!payload) return null;
    const user: User = { id: payload.sub, name: payload.name, email: payload.email, role: payload.role };
    const newToken = encodeToken(createPayload(user));
    localStorage.setItem('auth_token', newToken);
    return newToken;
  },

  /** Get the current authenticated user from storage (or null). */
  getCurrentUser(): { user: User; token: string } | null {
    const userStr = localStorage.getItem('auth_user');
    const token = localStorage.getItem('auth_token');
    if (!userStr || !token) return null;
    const user: User = JSON.parse(userStr);
    return { user, token };
  },
};
